### ISSUE TITLE
 Resizing windows 

### ISSUE THREAD

**Issue by vMeph** [custom-cards/text-element#3]
**Version of the cusom_component**

text-element.js  0.0.2

**Describe the bug**
text-element card,  in normal view text works perfect, but when resizing pages or on phone the text dont mantain the position.

**Comment by ludeeus** [comment]
using `px` insted of `%` make this look the same on different sizes
example:
```
        - type: picture-elements
          image: /local/files/LUfuf8ow.jpg
          elements:
            - type: custom:text-element
              text: "Episode:"
              style:
                color: red
                top: 47%
                left: 5px
                font-weight: 600
                transform: none
            - type: custom:state-attribute-element
              entity: sensor.tautulli__ludeeus
              attribute: s_senum_e
              style:
                top: 47%
                left: 70px
                transform: none
```
give:
with `panel:true`
![image](https://user-images.githubusercontent.com/15093472/43200151-c5abbc84-9014-11e8-87ef-6b6b96587e36.png)

with `panel:false`
![image](https://user-images.githubusercontent.com/15093472/43200157-d32ded14-9014-11e8-8bad-9f693208a192.png)

on iOS:
![image](https://user-images.githubusercontent.com/15093472/43200169-e1f0236c-9014-11e8-8461-4eafef0a0bef.png)
